### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by picsi** [mitchellurgero/QvitterNotify#1]
Hopefully one that is compatible with qvitter's license :)

**Comment by mitchellurgero** [comment]
LOL I haven't decided on a license yet. will most likely be MIT License. Which is compatible with Qvitter's license as well. That being said I believe in GitHub's ToS if no license is found it is assumed to be GPL or something to that affect? I might be wrong on that. Anyhow thanks for the info - I will look into incorporating a license soon into all my github projects. :) (Some of them right now are not technically "licensed" yet as they do not include a "license.md" file..)
